-- Real, publicly-known luxury brands from Zoe's target list (spec §2/§22).
-- Reference data only (name/category/official domain) — no fabricated PR
-- contacts, no invented sampling programs. relationship_stage stays
-- 'target' and sampling_program stays false until verified by real research.

insert into luxury_brands (name, category, luxury_tier, website, relationship_stage) values
  ('Chanel', 'fragrance', 'luxury', 'https://www.chanel.com', 'target'),
  ('Dior', 'fragrance', 'luxury', 'https://www.dior.com', 'target'),
  ('Tom Ford', 'fragrance', 'luxury', 'https://www.tomford.com', 'target'),
  ('Hermès', 'fragrance', 'luxury', 'https://www.hermes.com', 'target'),
  ('Maison Francis Kurkdjian', 'fragrance', 'luxury', 'https://www.franciskurkdjian.com', 'target'),
  ('Creed', 'fragrance', 'luxury', 'https://www.creedboutique.com', 'target'),
  ('Parfums de Marly', 'fragrance', 'luxury', 'https://www.parfums-de-marly.com', 'target'),
  ('Byredo', 'fragrance', 'luxury', 'https://www.byredo.com', 'target'),
  ('Le Labo', 'fragrance', 'luxury', 'https://www.lelabofragrances.com', 'target'),
  ('Diptyque', 'fragrance', 'luxury', 'https://www.diptyqueparis.com', 'target'),
  ('Jo Malone London', 'fragrance', 'luxury', 'https://www.jomalone.com', 'target'),
  ('Kilian Paris', 'fragrance', 'luxury', 'https://www.bykilian.com', 'target'),
  ('Guerlain', 'fragrance', 'luxury', 'https://www.guerlain.com', 'target'),
  ('Amouage', 'fragrance', 'luxury', 'https://www.amouage.com', 'target'),
  ('Initio Parfums Prives', 'fragrance', 'luxury', 'https://www.initio-parfums-prives.com', 'target'),
  ('Ex Nihilo', 'fragrance', 'luxury', 'https://www.exnihilo-paris.com', 'target'),
  ('Maison Margiela Fragrances', 'fragrance', 'luxury', 'https://www.maisonmargiela-fragrances.com', 'target'),

  ('Gucci', 'fashion', 'luxury', 'https://www.gucci.com', 'target'),
  ('Prada', 'fashion', 'luxury', 'https://www.prada.com', 'target'),
  ('Saint Laurent', 'fashion', 'luxury', 'https://www.ysl.com', 'target'),
  ('Louis Vuitton', 'fashion', 'luxury', 'https://www.louisvuitton.com', 'target'),
  ('Loewe', 'fashion', 'luxury', 'https://www.loewe.com', 'target'),
  ('Bottega Veneta', 'fashion', 'luxury', 'https://www.bottegaveneta.com', 'target'),
  ('Jacquemus', 'fashion', 'luxury', 'https://www.jacquemus.com', 'target'),
  ('Toteme', 'fashion', 'premium', 'https://www.toteme-studio.com', 'target'),
  ('Khaite', 'fashion', 'premium', 'https://www.khaite.com', 'target'),
  ('Anine Bing', 'fashion', 'premium', 'https://www.aninebing.com', 'target'),
  ('Frame', 'fashion', 'premium', 'https://www.frame-store.com', 'target'),
  ('Cult Gaia', 'fashion', 'premium', 'https://www.cultgaia.com', 'target'),

  ('La Mer', 'beauty', 'luxury', 'https://www.cremedelamer.com', 'target'),
  ('Augustinus Bader', 'beauty', 'luxury', 'https://www.augustinusbader.com', 'target'),
  ('Chanel Beauty', 'beauty', 'luxury', 'https://www.chanel.com', 'target'),
  ('Dior Beauty', 'beauty', 'luxury', 'https://www.dior.com', 'target'),
  ('Armani Beauty', 'beauty', 'luxury', 'https://www.armanibeauty.com', 'target'),
  ('YSL Beauty', 'beauty', 'luxury', 'https://www.yslbeauty.com', 'target'),
  ('Tom Ford Beauty', 'beauty', 'luxury', 'https://www.tomford.com', 'target'),
  ('Westman Atelier', 'beauty', 'premium', 'https://www.westman-atelier.com', 'target'),
  ('Hourglass Cosmetics', 'beauty', 'premium', 'https://www.hourglasscosmetics.com', 'target'),
  ('Charlotte Tilbury', 'beauty', 'premium', 'https://www.charlottetilbury.com', 'target'),
  ('Sisley Paris', 'beauty', 'luxury', 'https://www.sisley-paris.com', 'target'),
  ('Oribe', 'beauty', 'premium', 'https://www.oribe.com', 'target'),
  ('Kérastase', 'beauty', 'premium', 'https://www.kerastase.com', 'target'),

  ('Hermès Home', 'home', 'luxury', 'https://www.hermes.com', 'target'),
  ('Loewe Home Scents', 'home', 'luxury', 'https://www.loewe.com', 'target'),
  ('Diptyque Home', 'home', 'luxury', 'https://www.diptyqueparis.com', 'target'),
  ('Jo Malone Home', 'home', 'luxury', 'https://www.jomalone.com', 'target'),
  ('Jonathan Adler', 'home', 'premium', 'https://www.jonathanadler.com', 'target'),
  ('RH (Restoration Hardware)', 'home', 'premium', 'https://www.rh.com', 'target'),
  ('Le Creuset', 'home', 'premium', 'https://www.lecreuset.com', 'target'),
  ('Smeg', 'home', 'premium', 'https://www.smeg.com', 'target'),
  ('Dyson', 'home', 'premium', 'https://www.dyson.com', 'target');
